#!/usr/bin/python

import socket

mysock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
socket.setdefaulttimeout(3)
#socket.AF_INET is for the IP_Address ipv4
#SOCK_STREAM is for TCP

host = raw_input("[*]Please Enter The Host To Scan:")

def portscanner(port):
    if mysock.connect_ex((host,port)):
        print "Port %d is Closed" % (port)
    else:
        print "Port %d is Open" % (port)

for port in range(1,65535):
	portscanner(port)
